# Generated by Django 5.1.3 on 2024-12-06 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('tipo_doc', models.CharField(max_length=50)),
                ('doc_ident', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('dt_nac', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ddd', models.CharField(blank=True, max_length=5, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_pes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='endereco', serialize=False, to='registry.pessoa')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id_mun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='registry.municipio'),
        ),
    ]
